CREATE DATABASE dbProject4

use dbProject4 create TABLE MOVIE (
	MOVIETITLE VARCHAR(40) NOT NULL,
	PRODUCER VARCHAR(40) NOT NULL,
	RELEASEDATE DATE NOT NULL,
	RUNTIME TIME NOT NULL,
	BUDGET INT NOT NULL,
	GROSS INT NOT NULL,
);

use dbProject4 create TABLE ACTEDIN (
	ACTOR VARCHAR(40) NOT NULL,
	MOVIE VARCHAR(40) NOT NULL,
	PRODUCER VARCHAR(40) NOT NULL,
	PAY INT NOT NULL
);

use dbProject4 create TABLE ACTOR (
	NAME VARCHAR(40) NOT NULL,
);

use dbProject4 create TABLE PRODUCER (
	PRODUCERNAME VARCHAR(40) NOT NULL,
);
