using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DBProject.Models
{
    public class Actor
    {
        int ActorID { get; set; } // ActorID. Autogenerated. PK
        string FirstName { get; set; } // actor's first name
        string LastName { get; set; } // actor's last name

    }
}